name: dr_appoint_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  checkout_screen_ui: ^0.1.3
  cool_alert: ^2.0.1
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_loading_button: ^0.0.2
  flutter_login: ^4.1.1
  flutter_text_box: ^0.0.1
  fluttertoast: ^8.2.1
  loading_animation_widget: ^1.2.0+4
  shaky_animated_listview: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
